 import {
  Image as ImageIcon,
  RefreshCw,
  FileText,
  Scissors,
  Type,
  QrCode,
  Braces,
  Lock,
  Link2,
  Hash,
  Clock3,
  ShieldCheck,
  Code2,
  Database,
  Palette,
  KeyRound,
} from "lucide-react";
export const tools = [
{
  name: "Image Compressor",
  slug: "image-compressor",
  href: "/tools/image-compressor",
  icon: ImageIcon,
  color: "from-blue-500 to-cyan-400",
  desc: "Compress JPG, PNG and WebP images without losing quality.",
  category: "Image Tools",
  featured: true,
  keywords: [
    "image compressor",
    "compress image",
    "reduce image size",
    "jpg compressor",
    "png compressor",
    "webp compressor",
  ],
},
{
  name: "Image Converter",
  slug: "image-convertor",
  href: "/tools/image-convertor",
  icon: RefreshCw,
  color: "from-sky-500 to-blue-400",
  desc: "Convert images between JPG, PNG, WebP and other formats.",
  category: "Image Tools",
  featured: true,
  keywords: [
    "image converter",
    "jpg to png",
    "png to jpg",
    "webp converter",
    "convert image online",
  ],
},
{
  name: "PDF Merger",
  slug: "pdf-merger",
  href: "/tools/pdf-merger",
  icon: FileText,
  color: "from-red-500 to-orange-400",
  desc: "Merge multiple PDF files into one document online.",
  category: "PDF Tools",
  featured: true,
  keywords: [
    "merge pdf",
    "pdf merger",
    "combine pdf",
    "join pdf",
    "merge pdf online",
  ],
},
{
  name: "PDF Splitter",
  slug: "pdf-splitter",
  href: "/tools/pdf-splitter",
  icon: Scissors,
  color: "from-orange-500 to-yellow-400",
  desc: "Split PDF pages quickly and securely.",
  category: "PDF Tools",
  featured: true,
  keywords: [
    "split pdf",
    "pdf splitter",
    "extract pdf pages",
    "separate pdf",
    "pdf split online",
  ],
},
{
  name: "Word Counter",
  slug: "word-counter",
  href: "/tools/word-counter",
  icon: Type,
  color: "from-green-500 to-emerald-400",
  desc: "Count words, characters, sentences and paragraphs instantly.",
  category: "Text Tools",
  featured: true,
  keywords: [
    "word counter",
    "character counter",
    "text counter",
    "count words",
    "online word counter",
  ],
},
{
  name: "QR Generator",
  slug: "qr-generator",
  href: "/tools/qr-generator",
  icon: QrCode,
  color: "from-purple-500 to-pink-400",
  desc: "Generate custom QR codes for URLs, text and more.",
  category: "Image Tools",
  featured: true,
  keywords: [
    "qr generator",
    "create qr code",
    "free qr code generator",
    "qr maker",
    "online qr generator",
  ],
},
{
  name: "JSON Formatter",
  slug: "json-formatter",
  href: "/tools/json-formatter",
  icon: Braces,
  color: "from-cyan-500 to-blue-400",
  desc: "Beautify, format and organize JSON data online.",
  category: "Developer Tools",
  featured: true,
  keywords: [
    "json formatter",
    "beautify json",
    "format json",
    "json beautifier",
    "pretty json",
  ],
},
{
  name: "Base64 Encoder",
  slug: "base64-encoder",
  href: "/tools/base64-encoder",
  icon: Lock,
  color: "from-indigo-500 to-purple-400",
  desc: "Encode and decode Base64 strings instantly.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "base64 encoder",
    "base64 decoder",
    "encode base64",
    "decode base64",
    "base64 online",
  ],
},
{
  name: "Text Case Converter",
  slug: "text-case-converter",
  href: "/tools/text-case-converter",
  icon: Type,
  color: "from-emerald-500 to-green-400",
  desc: "Convert text to uppercase, lowercase, title case and more.",
  category: "Text Tools",
  featured: false,
  keywords: [
    "text case converter",
    "uppercase converter",
    "lowercase converter",
    "title case",
    "case converter",
  ],
},
{
  name: "Lorem Ipsum Generator",
  slug: "lorem-ipsum-generator",
  href: "/tools/lorem-ipsum-generator",
  icon: FileText,
  color: "from-pink-500 to-rose-400",
  desc: "Generate Lorem Ipsum placeholder text instantly.",
  category: "Text Tools",
  featured: false,
  keywords: [
    "lorem ipsum",
    "lorem ipsum generator",
    "placeholder text",
    "dummy text",
    "generate lorem ipsum",
  ],
},
{
  name: "URL Encoder / Decoder",
  slug: "url-encoder-decoder",
  href: "/tools/url-encoder-decoder",
  icon: Link2,
  color: "from-violet-500 to-fuchsia-400",
  desc: "Encode and decode URLs safely for web applications.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "url encoder",
    "url decoder",
    "encode url",
    "decode url",
    "url encode online",
  ],
},
{
  name: "UUID Generator",
  slug: "uuid-generator",
  href: "/tools/uuid-generator",
  icon: ShieldCheck,
  color: "from-teal-500 to-cyan-400",
  desc: "Generate secure UUID and GUID values online.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "uuid generator",
    "guid generator",
    "random uuid",
    "generate uuid",
    "uuid online",
  ],
},
{
  name: "Hash Generator",
  slug: "hash-generator",
  href: "/tools/hash-generator",
  icon: Hash,
  color: "from-yellow-500 to-orange-400",
  desc: "Generate MD5, SHA1 and SHA256 hash values online.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "hash generator",
    "md5 generator",
    "sha256 generator",
    "sha1 hash",
    "online hash",
  ],
},
{
  name: "Timestamp Converter",
  slug: "timestamp-converter",
  href: "/tools/timestamp-converter",
  icon: Clock3,
  color: "from-lime-500 to-green-400",
  desc: "Convert Unix timestamps into readable dates instantly.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "timestamp converter",
    "unix timestamp",
    "epoch converter",
    "unix time converter",
    "timestamp online",
  ],
},
{
  name: "JWT Decoder",
  slug: "jwt-decoder",
  href: "/tools/jwt-decoder",
  icon: ShieldCheck,
  color: "from-purple-500 to-indigo-400",
  desc: "Decode and inspect JWT tokens securely.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "jwt decoder",
    "decode jwt",
    "jwt parser",
    "jwt token decoder",
    "jwt online",
  ],
},
{
  name: "Regex Tester",
  slug: "regex-tester",
  href: "/tools/regex-tester",
  icon: Code2,
  color: "from-pink-500 to-purple-400",
  desc: "Test and debug regular expressions online.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "regex tester",
    "regular expression tester",
    "regex online",
    "regex checker",
    "regex validator",
  ],
},
{
  name: "HTML Encoder / Decoder",
  slug: "html-encoder-decoder",
  href: "/tools/html-encoder-decoder",
  icon: Code2,
  color: "from-blue-500 to-indigo-400",
  desc: "Encode and decode HTML entities instantly.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "html encoder",
    "html decoder",
    "encode html",
    "decode html",
    "html entities",
  ],
},
{
  name: "CSS Minifier",
  slug: "css-minifier",
  href: "/tools/css-minifier",
  icon: Palette,
  color: "from-rose-500 to-pink-400",
  desc: "Minify CSS code to reduce file size.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "css minifier",
    "minify css",
    "compress css",
    "css optimizer",
    "css compressor",
  ],
},
{
  name: "JS Minifier",
  slug: "js-minifier",
  href: "/tools/js-minifier",
  icon: Code2,
  color: "from-yellow-500 to-amber-400",
  desc: "Minify JavaScript code for better performance.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "javascript minifier",
    "js minifier",
    "minify javascript",
    "compress js",
    "javascript optimizer",
  ],
},
{
  name: "SQL Formatter",
  slug: "sql-formatter",
  href: "/tools/sql-formatter",
  icon: Database,
  color: "from-green-500 to-teal-400",
  desc: "Beautify and format SQL queries online.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "sql formatter",
    "format sql",
    "sql beautifier",
    "sql pretty print",
    "online sql formatter",
  ],
},
{
  name: "Remove Duplicate Lines",
  slug: "remove-duplicate-lines",
  href: "/tools/remove-duplicate-lines",
  icon: FileText,
  color: "from-red-500 to-pink-400",
  desc: "Remove duplicate lines from text instantly.",
  category: "Text Tools",
  featured: false,
  keywords: [
    "remove duplicate lines",
    "duplicate remover",
    "text duplicate remover",
    "remove repeated lines",
    "text cleaner",
  ],
},
{
  name: "Sort Lines",
  slug: "sort-lines",
  href: "/tools/sort-lines",
  icon: FileText,
  color: "from-cyan-500 to-sky-400",
  desc: "Sort text lines alphabetically in seconds.",
  category: "Text Tools",
  featured: false,
  keywords: [
    "sort lines",
    "sort text",
    "alphabetical sorter",
    "text sorter",
    "sort words",
  ],
},
{
  name: "Reverse Text",
  slug: "reverse-text",
  href: "/tools/reverse-text",
  icon: RefreshCw,
  color: "from-orange-500 to-red-400",
  desc: "Reverse words, sentences and characters instantly.",
  category: "Text Tools",
  featured: false,
  keywords: [
    "reverse text",
    "text reverser",
    "reverse words",
    "reverse string",
    "flip text",
  ],
},
{
  name: "Slug Generator",
  slug: "slug-generator",
  href: "/tools/slug-generator",
  icon: Link2,
  color: "from-violet-500 to-purple-400",
  desc: "Generate clean SEO-friendly URL slugs.",
  category: "Text Tools",
  featured: true,
  keywords: [
    "slug generator",
    "seo slug",
    "url slug",
    "slug maker",
    "generate slug",
  ],
},
{
  name: "JSON Validator",
  slug: "json-validator",
  href: "/tools/json-validator",
  icon: Braces,
  color: "from-blue-500 to-cyan-400",
  desc: "Validate JSON and detect syntax errors instantly.",
  category: "Developer Tools",
  featured: true,
  keywords: [
    "json validator",
    "validate json",
    "json checker",
    "json syntax validator",
    "online json validator",
  ],
},
{
  name: "URL Parser",
  slug: "url-parser",
  href: "/tools/url-parser",
  icon: Link2,
  color: "from-green-500 to-cyan-400",
  desc: "Parse and analyze URL components online.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "url parser",
    "parse url",
    "url analyzer",
    "url components",
    "online url parser",
  ],
},
{
  name: "HTML Minifier",
  slug: "html-minifier",
  href: "/tools/html-minifier",
  icon: Code2,
  color: "from-pink-500 to-red-400",
  desc: "Minify HTML code for faster web pages.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "html minifier",
    "minify html",
    "compress html",
    "html optimizer",
    "html compressor",
  ],
},
{
  name: "XML Formatter",
  slug: "xml-formatter",
  href: "/tools/xml-formatter",
  icon: Database,
  color: "from-indigo-500 to-blue-400",
  desc: "Beautify and format XML documents online.",
  category: "Developer Tools",
  featured: false,
  keywords: [
    "xml formatter",
    "format xml",
    "xml beautifier",
    "pretty xml",
    "online xml formatter",
  ],
  },
  {
  name: "Password Generator",
  href: "/tools/password-generator",
  icon: KeyRound,
  color: "from-amber-500 to-yellow-400",
  desc: "Generate strong and secure passwords instantly.",
  category: "Developer Tools"
  },
  {
  name: "Image Resizer",
  slug: "image-resizer",
  href: "/tools/image-resizer",
  icon: ImageIcon,
  color: "from-cyan-500 to-blue-500",
  desc: "Resize JPG, PNG and WebP images instantly online.",
  category: "Image Tools",
  featured: false,
  keywords: [
    "image resizer",
    "resize image",
    "resize images online",
    "jpg resizer",
    "png resizer",
    "webp resizer",
    "photo resizer",
    "picture resizer",
    "change image dimensions",
    "online image resizer",
  ],
},
];